<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuAdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'menu_name' => 'Menu',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/menu',
                'is_active' => 1,
                'menu_order' => 1,
                'menu_target' => 'menu',
                'icon' => 'fa fa-bars',
            ],
            [
                'menu_name' => 'Danh sách menu',
                'level' => 2,
                'parent_id' => 1,
                'route_name' => 'admin/menu',
                'is_active' => 1,
                'menu_order' => 2,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Người dùng',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/user',
                'is_active' => 1,
                'menu_order' => 3,
                'menu_target' => 'user',
                'icon' => 'fa fa-user-shield',
            ],
            [
                'menu_name' => 'Danh sách người dùng',
                'level' => 2,
                'parent_id' => 3,
                'route_name' => 'admin/user',
                'is_active' => 1,
                'menu_order' => 4,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Bài viết',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/post',
                'is_active' => 1,
                'menu_order' => 5,
                'menu_target' => 'post',
                'icon' => 'fa fa-newspaper',
            ],
            [
                'menu_name' => 'Danh sách bài viết',
                'level' => 2,
                'parent_id' => 5,
                'route_name' => 'admin/post',
                'is_active' => 1,
                'menu_order' => 6,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Dịch vụ',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/service',
                'is_active' => 1,
                'menu_order' => 7,
                'menu_target' => 'service',
                'icon' => 'fa fa-tooth',
            ],
            [
                'menu_name' => 'Danh mục dịch vụ',
                'level' => 2,
                'parent_id' => 7,
                'route_name' => 'admin/category-service',
                'is_active' => 1,
                'menu_order' => 8,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Danh sách dịch vụ',
                'level' => 2,
                'parent_id' => 7,
                'route_name' => 'admin/service',
                'is_active' => 1,
                'menu_order' => 9,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Bác sĩ',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/doctor',
                'is_active' => 1,
                'menu_order' => 10,
                'menu_target' => 'doctor',
                'icon' => 'fa fa-user-md',
            ],
            [
                'menu_name' => 'Danh sách bác sĩ',
                'level' => 2,
                'parent_id' => 10,
                'route_name' => 'admin/doctor',
                'is_active' => 1,
                'menu_order' => 11,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Danh sách bệnh án',
                'level' => 2,
                'parent_id' => 10,
                'route_name' => 'admin/doctor/benh-an',
                'is_active' => 1,
                'menu_order' => 12,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Tiếp tân',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/receptionist',
                'is_active' => 1,
                'menu_order' => 13,
                'menu_target' => 'receptionist',
                'icon' => 'fa fa-user-nurse',
            ],
            [
                'menu_name' => 'Danh sách tiếp tân',
                'level' => 2,
                'parent_id' => 13,
                'route_name' => 'admin/receptionist',
                'is_active' => 1,
                'menu_order' => 14,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Danh sách hóa đơn',
                'level' => 2,
                'parent_id' => 13,
                'route_name' => 'admin/receptionist/invoice',
                'is_active' => 1,
                'menu_order' => 15,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Câu hỏi thường gặp',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/faq',
                'is_active' => 1,
                'menu_order' => 16,
                'menu_target' => 'faq',
                'icon' => 'fa fa-question-circle',
            ],
            [
                'menu_name' => 'Danh sách câu hỏi',
                'level' => 2,
                'parent_id' => 16,
                'route_name' => 'admin/faq',
                'is_active' => 1,
                'menu_order' => 17,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Thông báo',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/notification',
                'is_active' => 1,
                'menu_order' => 18,
                'menu_target' => 'notification',
                'icon' => 'fa fa-bell',
            ],
            [
                'menu_name' => 'Danh sách thông báo',
                'level' => 2,
                'parent_id' => 18,
                'route_name' => 'admin/notification',
                'is_active' => 1,
                'menu_order' => 19,
                'menu_target' => null,
                'icon' => null,
            ],
            [
                'menu_name' => 'Tin nhắn',
                'level' => 1,
                'parent_id' => 0,
                'route_name' => 'admin/message',
                'is_active' => 1,
                'menu_order' => 20,
                'menu_target' => 'message',
                'icon' => 'fa fa-envelope',
            ],
            [
                'menu_name' => 'Danh sách tin nhắn',
                'level' => 2,
                'parent_id' => 20,
                'route_name' => 'admin/message',
                'is_active' => 1,
                'menu_order' => 21,
                'menu_target' => null,
                'icon' => null,
            ],
        ];

        \DB::table('menu_admins')->insertOrIgnore($data);
    }
}
